services:
  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
      target: ${COMPOSE_PROJECT_NAME}
    environment:
      DB__NAME: ${DB__NAME}
      DB__USER: ${DB__USER}
      DB__PASSWORD: ${DB__PASSWORD}
      DB__HOST: pg
    depends_on:
      pg:
        condition: service_healthy
    volumes:
      - ./coverage:/app/coverage

  pg:
    image: postgres:17.4
    environment:
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      start_period: 3s
      interval: 10s
      timeout: 3s
      retries: 3
